# Generated by Django 5.1.2 on 2025-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_target_minutes',
            field=models.PositiveIntegerField(default=300, help_text='Objetivo semanal medido en minutos. '),
        ),
    ]
