# Generated by Django 4.2.7 on 2025-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='description',
            new_name='professor_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='next_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
