# Generated by Django 5.1.2 on 2026-02-03 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('routineBlock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales (subject, duration, etc.)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('key_habit_reminder', 'Recordatorio de Hábito Clave'), ('weekly_challenge_reminder', 'Recordatorio de Desafío Semanal'), ('weekly_objectives_reminder', 'Recordatorio de Objetivos Semanales'), ('weekly_summary', 'Resumen Semanal')], default='key_habit_reminder', help_text='Tipo de notificación enviada', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text='ID del objeto relacionado (hábito, objetivo, desafío)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando el email fue enviado exitosamente', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', help_text='Estado del envío', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, help_text='Mensaje del recordatorio (para compatibilidad)', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora programada (para compatibilidad)', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', 'status'], name='notificatio_user_id_0a278f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_8ddc07_idx'),
        ),
    ]
