# Generated by Django 5.2.2 on 2025-06-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('routineBlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='routine_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='routineBlock.routineblock'),
        ),
    ]
