# Generated by Django 5.1.2 on 2026-01-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklychallenge',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
