# Generated by Django 5.1.2 on 2025-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
    ]
