# Generated by Django 5.1.2 on 2025-12-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_weeklyobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyobjective',
            name='area',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='weeklyobjective',
            name='icon',
            field=models.CharField(blank=True, default='⚡', max_length=10),
        ),
    ]
