# Generated by Django 5.1.2 on 2026-01-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_weeklyobjective_area_weeklyobjective_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyobjective',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyobjective',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
