# Generated by Django 5.1.2 on 2026-01-25 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_weeklyobjective_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyObjectiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, default='General', max_length=100)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_objective_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
