# Generated by Django 5.2.2 on 2026-02-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklychallenge',
            options={'ordering': ['-week_start']},
        ),
        migrations.RemoveField(
            model_name='weeklychallenge',
            name='completed_days',
        ),
        migrations.RemoveField(
            model_name='weeklychallenge',
            name='required_pomodoros_per_day',
        ),
        migrations.RemoveField(
            model_name='weeklychallenge',
            name='target_days',
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='challenge_type',
            field=models.CharField(choices=[('marathon_productivity', 'Marathon Productivity'), ('focus_deep_work', 'Focus Deep Work'), ('subject_focus', 'Subject Focus'), ('early_start', 'Early Start'), ('strong_finish', 'Strong Finish'), ('quality_over_quantity', 'Quality Over Quantity'), ('clean_focus', 'Clean Focus')], default='marathon_productivity', help_text='Type of challenge for this week', max_length=30),
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='current_value',
            field=models.FloatField(default=0.0, help_text='Current progress value'),
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='target_value',
            field=models.FloatField(default=1.0, help_text='Target value to achieve'),
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
