# Generated by Django 5.1.2 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("completed", "Completado"),
                    ("missed", "Vencido"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "status", "date"], name="events_user_status_date_idx"),
        ),
    ]
