# Generated by Django 5.1.2 on 2026-01-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_language'),
    ]

    operations = [
    ]
