# Generated by Django 5.1.2 on 2026-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone (e.g., America/Argentina/Buenos_Aires)", max_length=50),
        ),
    ]
