# Generated by Django 5.1.2 on 2026-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text="User's country for automatic timezone setting", max_length=100, null=True),
        ),
    ]
