# Generated by Django 5.1.2 on 2026-01-15 13:07

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_enable_pgvector'),
    ]

    operations = [
        VectorExtension()
    ]
