# Generated by Django 5.1.2 on 2026-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_country_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='AR', help_text='User country (ISO code)', max_length=100),
            preserve_default=False,
        ),
    ]
