# Generated by Django 5.1.2 on 2026-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Preferencias de notificación por email (estructura con keys: *_enabled y *_hour)'),
        ),
    ]
