# Generated by Django 5.1.2 on 2026-02-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auth_tokens_and_password_resets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='user_authto_user_id_2866b7_idx',
            old_name='user_authto_user_id_7b2e49_idx',
        ),
        migrations.RenameIndex(
            model_name='authtoken',
            new_name='user_authto_expires_adc6ce_idx',
            old_name='user_authto_expires_5c4043_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='user_passwo_user_id_9cadeb_idx',
            old_name='user_passwo_user_id_6d04c3_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='user_passwo_token_h_d06dd1_idx',
            old_name='user_passwo_token_h_6c2666_idx',
        ),
    ]
